Repository kubescape/config-service, pull requests merged in 2023-11, with the labels that each got.

#93 Add list search for repositories
  routes/v1/repository/routes.go
  service_test.go
Labels: enhancement

#94 bump armo api version to version with severity score
  go.mod
  go.sum
Labels: enhancement

#96 add admin apis for bulk set severity
  admin_test.go
  db/utils.go
  routes/v1/admin/routes.go
  types/types.go
Labels: enhancement, Possible security concern

#97 support date field type using schema info
  db/utils.go
  handlers/handlers.go
  handlers/v2ListRequest.go
  routes/v1/vulnerability_exception/routes.go
  service_test.go
  test_data/vulnerabilityPolicies.json
  testers_test.go
  types/api_info.go
  utils/utils.go
Labels: enhancement

#98 add posture policies date field schema info
  routes/v1/posture_exception/routes.go
Labels: enhancement

#99 Fix inner filters case of OR filter with multiple filter
  db/filter.go
  service_test.go
  test_data/posturePolicies.json
  testers_test.go
Labels: bug_fix, tests
