Repository kubescape/config-service, pull requests merged in 2023-09, with the labels that each got.

#87 SUB-2413 | enable v2 list search for clusters
  routes/v1/cluster/routes.go
  service_test.go
  test_data/clusters.json
Labels: enhancement

#88 update armoapi to support attackChainsLastScan in customerState
  go.mod
  go.sum
Labels: enhancement

#86 Support rename for collaboration
  db/filter.go
  db/mongo/index.go
  handlers/routes.go
  handlers/validate.go
  routes/v1/collaboration_config/routes.go
  routes/v1/posture_exception/routes.go
  routes/v1/vulnerability_exception/routes.go
  service_test.go
  testers_test.go
  types/types.go
Labels: enhancement

#89 Admin API to query/aggregate customers documents
  admin_test.go
  db/utils.go
  go.mod
  go.sum
  handlers/handlers.go
  handlers/routes.go
  routes/v1/admin/routes.go
  suite_test.go
  types/api_info.go
Labels: enhancement

#90 fix panic on out index range
  handlers/v2ListRequest.go
Labels: Bug fix

#91 Attack Chains scan metadata
  db/mongo/index.go
  go.mod
  go.sum
  routes/v1/attack_chains/routes.go
  routes/v1/attack_chains/validators.go
  service_test.go
  test_data/attack-chain-configs.json
  test_data/attack-chain-states.json
  types/types.go
Labels: Refactoring

#92 attack chains states - added unique name validator
  routes/v1/attack_chains/routes.go
  service_test.go
Labels: Refactoring
